### ISSUE TITLE
Zoom level of documents sometimes too small

### ISSUE THREAD

**Issue by MSchmidt** [PDF-Archiver/PDF-Archiver#108]
**Describe the bug**
Some documents open way too small. Like a tiny white rectangle in the middle of the grey area. Taking only like 5% of the available space.

**To Reproduce**
1. Select a document
2. View it in the main panel
3. Zooming in via Trackpad works fine
4. Switching to another document and coming back opens zoomed out again

**Expected behavior**
All documents should use the available space at least in height or weight.

**Screenshots**
<img width="1530" alt="Screenshot 2022-07-22 at 09 00 57" src="https://user-images.githubusercontent.com/38004/180382471-f7f2b93b-7715-4cab-a55a-45162493bfc9.png">

**Smartphone information:**
 - Device: MacBook Pro M1
 - OS: macOS 12.4
 - Version 3.5.3

**Comment by JulianKahnert** [comment]
Hi @MSchmidt,
thx for your feedback! This is fixed in 16dd463782ec43a065342a1997b7039d9901b83a and will be released in Version `3.6.0` 🙂
