### ISSUE TITLE
What about LaTeX export if you want to use it for papers as well?

### ISSUE THREAD

**Issue by micheld93** [PDF-Archiver/PDF-Archiver#11]
Hi, 

what do you think about a LaTeX/BIB export function? It would be useful because most papers are pdfs and PDF-Archiver would fit this application then very well. 

Wishes

**Comment by JulianKahnert** [comment]
Hi,

sorry for the late reply. Since the constraints of the archiving system are fixed, maybe this can be done within an external tool. Maybe you can join our [Slack](https://slackin-pdf-archiver.herokuapp.com/) and we can discuss it even further.

best
