### ISSUE TITLE
Font width calculation after OCR usually too small

### ISSUE THREAD

**Issue by thilo-hub** [PDF-Archiver/PDF-Archiver#111]
I noticed, that the calculated width of the oct'ed text using only the font-size is usually wrong/inaccurate.

see example:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/23134554/181380538-55524976-1cb8-4c8f-822b-1c484c46beec.png">

Using the patch below get's closer. I think the key.expansion is somehow useful. Though I do not yet fully understand why I need a scaling factor of 0.95 to have the drawing not being clipped/too wide.

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/23134554/181380890-b471f30d-24cb-4ba5-b7ce-f43111cf9be8.png">

Anyhow, nice code! Thank you

```
diff --git a/ArchiveCore/Sources/ArchiveBackend/PDFRendering/PDFProcessing.swift b/ArchiveCore/Sources/ArchiveBackend/PDFRendering/PDFProcessing.swift
index 8e32fbc..755d228 100644
--- a/ArchiveCore/Sources/ArchiveBackend/PDFRendering/PDFProcessing.swift
+++ b/ArchiveCore/Sources/ArchiveBackend/PDFRendering/PDFProcessing.swift
@@ -350,7 +350,11 @@ extension NSAttributedString {
         let fontName = Font.systemFont(ofSize: 0).fontName
         var attributes: [NSAttributedString.Key: Any] = [NSAttributedString.Key.foregroundColor: Color.clear]
         attributes[.font] = Font(named: fontName, fitting: text, into: size, with: attributes, options: .usesFontLeading)
+        let sw = NSAttributedString(string: text, attributes: attributes).size()
+        attributes[NSAttributedString.Key.expansion]=log(0.95 * (size.width)/(sw.width))
+        let sw1 = NSAttributedString(string: text, attributes: attributes).size()
 
+        print("Text: \(text)\n Old: \(sw) -> \(sw1)\n S:\(size)");
         return NSAttributedString(string: text, attributes: attributes)
     }
 }
```

**Comment by JulianKahnert** [comment]
Wow this looks awesome! This is (one of) the first time someone sees a bug and fixes it in PDF Archiver 😍🙏

If you want to, you could add a PR that implements your changes and I will review/test/merge it afterwards. ...to get 💯% OpenSource props 🙃🤩

**Comment by thilo-hub** [comment]
Echt jetzt?

Haette ich nicht gedacht. 
Ja kann ich machen, Im Augenblickk lern ich swift…. :-)
Und ich hab sowas ähnliches wie du gemacht, einen web-server der mittels sqlite & tesseract, alles was “reinfliegt” speichert, automatisch tags erstellt und “moeglischt” schnell eine Volltext suche auf die Daten macht.
Von daher bin ich an deinem Projekt interessiert!

Bietet sich (für mich) als alternative zum iCloud backup an.
(Ich kann aber auch power-point/word/zip/tar/… einladen.

Gruss
-------------------------------
Dipl. Ing. Thilo Jeremias
Hauptstraße 11
35466 Rabenau

T: +49 15782492240
