### ISSUE TITLE
Selected page in multi-page PDFs is kept, when moving to another file

### ISSUE THREAD

**Issue by janwh** [PDF-Archiver/PDF-Archiver#13]
**PDF Archiver version (PDF Archiver > About PDF Archiver):** Version 1.2.0 (28)

**Description of problem:**

The selected page number in multi-page PDFs is kept, when moving to another file, so the next PDF opens on that page as well (if and when the PDF has enough pages

**Expected:**

When jumping between PDF documents, I'd expect to always start from the first page, so the Archiver should move back to page 1 on the next selection

**Problem-relevant steps to reproduce:**

1. Select a document with more than 1 page in the file list
2. Move the preview viewframe to a page other than 1
3. Select *another* document with more than 1 page in the file list

**Additional info:**

When the second document has fewer pages, than the selected page in the first document, the *last* page in the second document is selected.

**Comment by JulianKahnert** [comment]
Hey @janwh 
Thanks for this issue! I‘ll review the problem in the next couple of days. 🙂

**Comment by JulianKahnert** [comment]
This issue will be fixed in the next release 😊
