### ISSUE TITLE
New document displayed three times

### ISSUE THREAD

**Issue by sohnemann** [PDF-Archiver/PDF-Archiver#16]
**Describe the bug**
After scanning, tagging and archiving a new document in the iOS app, it is shown as three separate items.
Also, selecting one of the three entries leads to weird behaviour in the app, with different views being shown.
When trying to delete one of the items, it shows the following error:
[Screenshot 1 - on Imgur](https://i.imgur.com/lkkwvpS.jpg)
Only restarting the app makes the unnessesary items disappear.

**To Reproduce**
1. Go to 'Scan'
2. Tap on 'Scan'
3. Scan the document
4. Tap 'Keep Scan'
5. Tap 'Save'
6. Go to 'Tag'
7. Add a description and tags
8. Tap on 'Add'
9. Go to 'Archive'
10. See the new document three times

**Expected behavior**
The document should only show up as a single item.

**Screenshots**
[Screenshot 2 - on Imgur](https://i.imgur.com/R6Mdu87.png)

**Smartphone information**
 - Device: [iPhone 7]
 - OS: [iOS 14.4]
 - Version [e.g. 3.2.4 (4)]

**Additional context**
N/A

**Comment by JulianKahnert** [comment]
Thx for your feedback this should not happen, obviously. I can not reproduce the problem here. Is it happening every time on your site?
Please send me your feedback at [mail@pdf-archiver.io](mailto:mail@pdf-archiver.io).

**Comment by JulianKahnert** [comment]
Closing this issue for now. Please let me know if you can reproduce it.

**Comment by 0nse** [comment]
I can confirm similar behaviour on my iPad: After I have scanned and tagged a document, it appears twice. If I delete one of the copies, the other won‘t open anymore and yield an error. If I close the app and open the app again, only a single file will be displayed.
