### ISSUE TITLE
[Enhancement] - Add setting to change default camera view to 'Auto' or 'Manual'

### ISSUE THREAD

**Issue by sohnemann** [PDF-Archiver/PDF-Archiver#17]
It would be great to be able to change the default behaviour of the camera view.
Right now it's always set to 'Auto' so I have to change it to 'Manual' every time.
Maybe this could be added in the 'More' menu.

**Comment by JulianKahnert** [comment]
Sadly this is not possible with current SDK APIs. 🙁
