### ISSUE TITLE
Rotation of document not saved

### ISSUE THREAD

**Issue by sohnemann** [PDF-Archiver/PDF-Archiver#18]
**Describe the bug**
I've created a new document and rotated it immediately. 
When adding tags, the rotation was reset.

**To Reproduce**
1. Go to 'Scan'
2. Tap on 'Scan'
3. Scan the document
4. Tap 'Keep Scan'
5. Tap on the scanned document in the lower right corner
6. Tap the 'Rotate' button
7. Tap 'Done'
8. Tap 'Save'
9. Go to 'Tag'
10. Add a description and tags 
11. See how it's no longer rotated
12. Tap 'Add
13. Go to 'Archive'
14. Select the document
15. See how it's no longer rotated

**Expected behavior**
After rotating and saving a document, the rotation should be kept.

**Screenshots**
N/A

**Smartphone information:**
 - Device: [e.g. iPhone 7]
 - OS: [e.g. iOS 14.4]
 - Version [e.g. 3.2.4 (4)]

**Additional context**

**Comment by JulianKahnert** [comment]
Thx for your feedback. I have saved it on my todo list.

**Comment by JulianKahnert** [comment]
This is fixed in 922aa80d7cdebe47a9572f145ef74c94ca369c1a and will be included in Version `3.2.5`. Thank you so much for creating this issues 🙂
