### ISSUE TITLE
[Enhancement] - Accept spaces in tags & honour original spelling

### ISSUE THREAD

**Issue by sohnemann** [PDF-Archiver/PDF-Archiver#20]
It would be a great enhancement if Tags would honour the original spelling.

For example:

'DE' becoming 'De'
'The Warehouse' becoming 'Thewarehouse'
'New Zealand' becomin 'Newzealand'

**Comment by JulianKahnert** [comment]
There is a fixed folder structure in as mentioned [here](https://juliankahnert.de/2018-03-03-pdf-archiver/). This naming convention must not be changed yet, to avoid inconsistencies.
Write me at [mai@pdf-archiver.io](mailto:mai@pdf-archiver.io) if you want to discuss this further.
