### ISSUE TITLE
Suggestion: Swap Done and Retake Buttons

### ISSUE THREAD

**Issue by kiliankoe** [PDF-Archiver/PDF-Archiver#21]
Hi!

I love the app. The only thing I keep on running into are the done and retake toolbar buttons in the document overview after scanning. I'm not sure if it's just me, but I pretty much always tap retake after I'm done, expecting the finish action to be on the right side. I feel like it's that way everywhere else.

![IMG_106A76D53FCD-1](https://user-images.githubusercontent.com/2625584/107875341-9e628e00-6ebf-11eb-9935-007deec29453.jpeg)

Thanks for considering 😊

**Comment by JulianKahnert** [comment]
Thx for you feedback! The scanning view is a component from the iOS SDK and sadly there is nothing I can do to change the order of the buttons:/

**Comment by kiliankoe** [comment]
Oh interesting, good to know! Guess it's time to submit feedback then 😅
