### ISSUE TITLE
Feature Request: Other storage locations like Tresorit or Nextcloud

### ISSUE THREAD

**Issue by Speedliner** [PDF-Archiver/PDF-Archiver#32]
It would be great to be able to connect other storages as well. I use [Tresorit](https://tresorit.com/de) (but also have a Nextcloud instance) and would rather store the PDF Archiver data there than in Apple's iCloud or locally on the device.

**Comment by JulianKahnert** [comment]
Hi @Speedliner ,
Since I'm the only maintainer of the project, this is currently out of scope of this hobby project. Sry

**Comment by 0nse** [comment]
Would it instead be possible to select a different storage location? Applications like Boxcryptor or Cryptomator nowadays integrate in the files app. However, I don‘t know if it just a path that one needs to configure or if it‘s an API that has to be integrated.

**Comment by tcurdt** [comment]
@0nse this will most likely not work if you are also using the iOS app
