### ISSUE TITLE
changing tags modifies PDF

### ISSUE THREAD

**Issue by tcurdt** [PDF-Archiver/PDF-Archiver#45]
**Describe the bug**

When I change the tags of a file it not only changes the filename, it also changes the keywords inside the PDF.
This means the SHA of the file changes. This is not desirable for an archive.

**To Reproduce**
1. Scan a PDF
2. Add some tags
3. Wait for the iCloud sync and note the md5/sha of the file
4. Remove a tag
5. Wait for the iCloud sync and note the md5/sha of the file

**Expected behavior**

The file should be renamed, but the file itself should not be modified.
The md5/sha should stay the same.

**Smartphone information:**
 - Device: iPhone 11
 - OS: 14.7.1
 - Version: 3.4.1 (1)

**Comment by JulianKahnert** [comment]
You can change this behavior by turning off the "Save Tags in PDF Metadata" Setting.
Please close this issue if it fixes your problem ☺️

**Comment by tcurdt** [comment]
Perfect! I didn't see those settings.

Since I am already in those settings. What do the "Require Document Tags" and "Require Document Specification" do?

I could only could come up with requiring 0+ vs 1+ tags - but I am a bit at a loss about the "specification".

**Comment by JulianKahnert** [comment]
These settings specify if you want to make sure that every document has tags/specification. With specification meaning a document description, e.g. "blue pullover".

**Comment by tcurdt** [comment]
So "with specification" means a description is required?
