### ISSUE TITLE
Don't know how, but lost a file.

### ISSUE THREAD

**Issue by mnott** [PDF-Archiver/PDF-Archiver#7]
Have 6 files, imported / tagged three, two got moved into the target folder, one just went missing.

**Comment by JulianKahnert** [comment]
Hey, thanks for reporting this issue:
could you please explain your workflow in detail?

**Comment by JulianKahnert** [comment]
Hey @mnott, I have just released a new version (1.1.3). Can you reproduce this problem on this version?

**Comment by JulianKahnert** [comment]
I am closing this since there is no new reaponse.
