### ISSUE TITLE
previous tags are not listed

### ISSUE THREAD

**Issue by jollijumper** [PDF-Archiver/PDF-Archiver#8]
I tagged several PDFs for example with "Bedienungsanleitung" and saved. But the previous tags are not listed in the search field.

If I use the search field nothing is shown.
If I type "Fi" an press enter. The tag "Bedien" appears in the top field. 

MacOS 10.3.3 

<img width="370" alt="bildschirmfoto 2018-03-11 um 14 24 11" src="https://user-images.githubusercontent.com/1527883/37253884-ede6cba0-2537-11e8-94fa-0a7afbe55231.png">

**Comment by JulianKahnert** [comment]
Hey there,
thank you for reporting this problem!
I am currently exploring this bug. Can you give me some more details. The following things would be very helpful:

* A list of the filenames in your archive
* The exact filename of the new document 

Does the Bug appear again after updating the tags (Hilfe > Tags aktualisieren)?

If yes: does a Reset of the settings (and setting the archive path again) fixes it?

**Comment by jollijumper** [comment]
Ähhhmmm really "Hilfe > Tags aktualisieren" ???
I can see nothing like this
<img width="354" alt="bildschirmfoto 2018-03-12 um 19 15 16" src="https://user-images.githubusercontent.com/1527883/37301745-c4773884-2629-11e8-88a7-8d14bdf1c3db.png">

"Hilfe > Einstellungen zurücksetzen" only resets the Archive path

I have only one file tagged: 
"2007-03-01--elv-akku-lade-center-alc-1010-expert-alc-2000-expert__bedienungsanleitung.pdf"

**Comment by JulianKahnert** [comment]
Dis you get the app from the App Store? If not, which commit are you on?

**Comment by jollijumper** [comment]
I build it yesterday by my own... Version 1.1.2 (13)
I guess its the latest commit.

**Comment by JulianKahnert** [comment]
Hey @jollijumper, I have just released a new version (1.1.3). Can you reproduce this problem on this version?

**Comment by jollijumper** [comment]
It work! Thanks.
Menu Item "Hilfe > Tags aktualisieren" is also available now.
But the About Dialog shows still "Version 1.1.2 (13)"

**Comment by JulianKahnert** [comment]
Happy to hear that 😊

hm the App Store Version should be 1.1.3.
If you want to, please join us in Slack:
<https://slackin-pdf-archiver.herokuapp.com/>
