### ISSUE TITLE
File cannot be deleted

### ISSUE THREAD

**Issue by FM-500** [PDF-Archiver/PDF-Archiver#81]
PDF folder is a network share on Synology, that is mounted via SMB on MacOS.

When trying to delete a file, the following error occurs:

`Error Domain=NSCocoaErrorDomain Code=3328 "„2019-08-08_150556_PDF_01.pdf“ konnte nicht in den Papierkorb bewegt werden, da auf dem Volume „pdf“ keiner vorhanden ist." UserInfo={NSURL=file:///Volumes/pdf/ARCHIV/2019-08-08_150556_PDF_01.pdf, NSUserStringVariant=(
Trash
), NSUnderlyingError=0x600002ffa580 {Error Domain=NSOSStatusErrorDomain Code=-120 "dirNFErr: Directory not found"}}`

I suspect, this is related to the network share, although the trash folder for this share actually exists. It is called "#recyle" and cannot be renamed on Synology.

**Comment by JulianKahnert** [comment]
Hi @FM-500,
I also assume that it is due to the network share or SMB. Unfortunately, I can not provide support for this, because I can not reproduce the error on my end. Sry 🙁
