### ISSUE TITLE
Feature Request: Load PDFs from predefined "untagged" folder on startup

### ISSUE THREAD

**Issue by jollijumper** [PDF-Archiver/PDF-Archiver#9]
Would be great for the workflow if an predefined default "untagged" folder will be opened right from startup of the app.

1. Scan to "untagged"
2. Open PDF-Archiver and start tagging without ⌘ o (and browsing)

**Comment by JulianKahnert** [comment]
Hey, thanks for this one! It is already in my todo list 😊
