### ISSUE TITLE
PDF verschlüsseln

### ISSUE THREAD

**Issue by BorussiaPlayer17** [PDF-Archiver/PDF-Archiver#96]
Hi,

erstmal danke für deine App.

Ich hätte da nur einen kleinen Verbesserung Vorschlag. Ich würde es toll finden PDFs mit einem Passwort schützen zu können. Vielleicht so das man es in der App hinterlegen kann und per FaceID öffnen könnte. 

Gruß

**Comment by JulianKahnert** [comment]
Moin,
das ist aktuell nicht geplant, aber du kannst dich gerne an dem Feature probieren! 🙂
